### ISSUE TITLE
Avoid local variables called "error"

### ISSUE THREAD

**Issue by fverdugo** [gridap/MiniQhull.jl#2]
@victorsndvg 

I have just realized that we are overwriting the name "error" here https://github.com/gridap/MiniQhull.jl/blob/6ebda257c8c6d664dc79437fd1f494862ef75f67/src/MiniQhull.jl#L14

could we rename the local variable as `ierror` in order not overwrite the name "error"  of the julia function?

**Comment by victorsndvg** [comment]
Yep, you are right.

I renamed the variable `error` to `ierror`in the main procedure (`_delaunay`) in 1fe2593
