### ISSUE TITLE
include license directly

### ISSUE THREAD

**Issue by tpapp** [gridap/MiniQhull.jl#4]
[LICENSE.md](https://github.com/gridap/MiniQhull.jl/blob/5c34dcc5ab83543dba030e1f305b8cd139585943/LICENSE.md) is currently a bit misleading: when people read

> under the X license

it usually refers to some specific license like MIT, Boost, AGPL, etc.

Of course it can easily be established that the current license is MIT, but it would be better to just include an MIT license in the LICENSE.md of this package. Linking to another file which may change is not ideal for a license.

**Comment by fverdugo** [comment]
The reason we are linking to a file is to easily maintain the licences of all our repos under github.com/gridap/

Essentially, we want the same licence for all these repos, thus having it in a single field + pointing from other repos when needed is the solution we have ended with.

Which solution do you use in similar situations?

**Comment by fverdugo** [comment]
I don't know if is possible to include the contents of a markdown file in another markdown file. This would do the job, but I have not found any easy way of doing this...

**Comment by tpapp** [comment]
Most packages (all I know of) just **copy** the license text directly into the file, [eg](https://github.com/timholy/Revise.jl/blob/master/LICENSE.md).

If you have already decided on a license, you could do the same. Ideally the license should not change very often so there should be no need to "maintain" it.

**Comment by fverdugo** [comment]
Is the problem related with the clause "distrubuted under the Gridap licence" ? since "Gridap license"  is not a standard licence ?

Would something like this be more acceptable?

>This repository belongs to the Gridap project and is distributed under the same licence as Gridap itself. See here further details:
>
>https://github.com/gridap/Gridap.jl/blob/master/LICENSE.md

**Comment by tpapp** [comment]
The main problem is that the license is not distributed with the code and can thus be changed independently. Someone could be using your code, and you could change the license to literally anything (I am not saying you would do this, but it is a possibility).

Again, what I am asking for is pretty standard; what you are doing is very unusual. I am not sure why you are not willing to do this if the package is otherwise intended to be free software --- do you want to change the license later to something more restrictive?

**Comment by fverdugo** [comment]
> The main problem is that the license is not distributed with the code and can thus be changed independently. Someone could be using your code, and you could change the license to literally anything (I am not saying you would do this, but it is a possibility).

I see, e.g., if you bundle the sources in a tar file, the licence info can be lost very easily if it is not copied there.  We have to change it.

> Again, what I am asking for is pretty standard; what you are doing is very unusual. I am not sure why you are not willing to do this if the package is otherwise intended to be free software --- do you want to change the license later to something more restrictive?

I just wanted to understand why our approach is problematic. Now, I see the point. We are happy to distribute our projects under the MIT licence as many people in the Julia community does. We hope this repo is useful to others in the same way many other julia packages are useful for us!

**Comment by santiagobadia** [comment]
I have created a script that automatically generates the licenses for all projects in github.com/gridap/
Now, the license file is included in each project.
