### ISSUE TITLE
Error on GitHub CI

### ISSUE THREAD

**Issue by mtsch** [gridap/MiniQhull.jl#9]
First of all, thank you for the great package! Having access to lightweight Delaunay triangulations in any dimension is invaluable to me.

The package works great on my machine and Travis (macOS and Linux), but when I try using it with GitHub actions with [BenchmarkCI.jl](https://github.com/tkf/BenchmarkCI.jl), I get `ERROR: QHULL WRAPPER is not properly loaded`.

This is `deps/build.log`:

```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/runner/.julia/packages/MiniQhull/TRNh0/deps/MiniQhullWrapper/build/CMakeFiles/CMakeOutput.log".
[ Info: MiniQhullWrapper root directory at: /home/runner/.julia/packages/MiniQhull/TRNh0/deps/MiniQhullWrapper
┌ Warning: Something wrong has happened while building MiniQhullWrapper
└ @ Main ~/.julia/packages/MiniQhull/TRNh0/deps/build.jl:55
┌ Info: QHULL configuration:
│ ==============================================
│   - QHULL_WRAPPER_FOUND    = false
│   - QHULL_WRAPPER_LIB_DIR  = /home/runner/.julia/packages/MiniQhull/TRNh0/deps/MiniQhullWrapper/build/lib
│   - QHULL_WRAPPER_LIB_NAME =
└   - QHULL_WRAPPER_LIB_PATH =
```

The other log `deps/MiniQhullWrapper/build/CMakeFiles/CMakeOutput.log` only says:

```
The system is: Linux - 5.4.0-1025-azure - x86_64
```

I tried looking around the internet and people say you get this error if `make` is not installed. When I tried running `which make` and `which gcc` in the script, both returned valid paths.

By the way, this is running on Julia 1.5, so `Qhull_jll` gets installed and I'm assuming I don't need to install any other dependencies.

I have zero experience with CMake, so I'm hoping you might have some ideas. It's also possible the problem is with CMake.jl, not MiniQhull.jl, but I figured I'd post it here first.

Thanks!

**Comment by mtsch** [comment]
I found the solution. If anyone else comes across something similar, you need to run this step in your action before you run anything that uses MiniQhull:
```
      - uses: julia-actions/julia-buildpkg@latest
```

**Comment by fverdugo** [comment]
@mtsch thanks for reporting!
